title: "Shahin Masoumi-Verki"
author: "Shahin Masoumi-Verki"
description: "Data Scientist | ML Engineer | Digital Twins | Dynamical Systems"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_excerpts: false
show_frame: true            # keep the boxed page style
show_sidebar: false
show_minimal: false

# Personal site
url: "https://shahin-smv93.github.io"
baseurl: ""

# Top navigation (these appear in the header)
navigation:
  - {title: "CV", url: "/assets/Masoumi-Verki_Shahin_CV.pdf"}
  - {file: "Projects.md", title: "Projects"}

# Remove header social icons (we show email/links on the page instead)
external: []

comments:
#  disqus_shortname: ""
#  isso_domain: ""

plugins:
 - jekyll-feed
