title: "Shahin Masoumi-Verki"
author: "Shahin Masoumi-Verki"
description: "Data Scientist | ML Engineer | Digital Twins | Dynamical Systems"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_excerpts: false
show_frame: true            # boxed page; header will be visually aligned via CSS
show_sidebar: false
show_minimal: false

# Site URL (personal site)
url: "https://shahin-smv93.github.io"
baseurl: ""

# Menu
navigation:                 # accepts {file, title, url, icon, sidebaricon}
  - {title: "CV", url: "/assets/Masoumi-Verki_Shahin_CV.pdf"}
  - {file: "Projects.md", title: "Projects"}

# Header icons (remove to hide the icons row in header)
external: []                # <- intentionally empty

comments:
#  disqus_shortname: ""
#  isso_domain: ""

plugins:
 - jekyll-feed
