title: "Shahin Masoumi-Verki"
author: "Shahin Masoumi-Verki"
description: "Data Scientist | ML Engineer | Digital Twins | Dynamical Systems"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: true             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "README.md", title: "About"}
 # - {file: "archive.html", title: "Home"}
  

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:shahinmasoumi93@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/shahin-smv93"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/shahin-masoumi-verki-326b41116/"}
  - {title: Google Scholar, icon: google, url: "https://scholar.google.com/citations?user=jnIYq4sAAAAJ&hl=en"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
